import type { Question, SubTheme } from "./types";

const quizBank: Record<SubTheme, Question[]> = {
  programming: [
    {
      id: "prg1",
      text: "Which data structure uses LIFO (Last In First Out) order?",
      options: ["Queue", "Stack", "Heap", "Tree"],
      correctIndex: 1,
    },
    {
      id: "prg2",
      text: 'What does "O(n log n)" represent in Big-O notation?',
      options: [
        "Constant time",
        "Linear time",
        "Linearithmic time",
        "Quadratic time",
      ],
      correctIndex: 2,
    },
    {
      id: "prg3",
      text: "Which programming paradigm treats computation as evaluation of mathematical functions?",
      options: ["OOP", "Procedural", "Functional", "Imperative"],
      correctIndex: 2,
    },
    {
      id: "prg4",
      text: "What is a closure in programming?",
      options: [
        "A function that calls itself",
        "A function with access to its outer scope",
        "A sealed class",
        "A binary operator",
      ],
      correctIndex: 1,
    },
    {
      id: "prg5",
      text: "Which sorting algorithm has the best average-case time complexity?",
      options: [
        "Bubble Sort",
        "Insertion Sort",
        "Merge Sort",
        "Selection Sort",
      ],
      correctIndex: 2,
    },
    {
      id: "prg6",
      text: "What does DRY stand for in software development?",
      options: [
        "Don't Repeat Yourself",
        "Dynamic Runtime Yielding",
        "Data Retrieval Yield",
        "Design Reuse Yield",
      ],
      correctIndex: 0,
    },
    {
      id: "prg7",
      text: "Which of these is NOT a primitive data type in most languages?",
      options: ["Integer", "Boolean", "Array", "Float"],
      correctIndex: 2,
    },
    {
      id: "prg8",
      text: "What is memoization?",
      options: [
        "Writing comments in code",
        "Caching function results for the same inputs",
        "Memory allocation",
        "Error logging",
      ],
      correctIndex: 1,
    },
    {
      id: "prg9",
      text: "A binary tree with all leaf nodes at the same depth is called?",
      options: [
        "Perfect binary tree",
        "Complete binary tree",
        "Full binary tree",
        "Balanced binary tree",
      ],
      correctIndex: 0,
    },
    {
      id: "prg10",
      text: "Which design pattern ensures a class has only one instance?",
      options: ["Factory", "Observer", "Singleton", "Decorator"],
      correctIndex: 2,
    },
  ],
  webdev: [
    {
      id: "web1",
      text: "What does CSS stand for?",
      options: [
        "Creative Style Sheets",
        "Cascading Style Sheets",
        "Computer Style Sheets",
        "Colorful Style Sheets",
      ],
      correctIndex: 1,
    },
    {
      id: "web2",
      text: 'Which HTTP status code means "Not Found"?',
      options: ["200", "301", "403", "404"],
      correctIndex: 3,
    },
    {
      id: "web3",
      text: "What is the virtual DOM in React?",
      options: [
        "A server-side rendering technique",
        "A lightweight copy of the real DOM",
        "A CSS framework",
        "A database abstraction",
      ],
      correctIndex: 1,
    },
    {
      id: "web4",
      text: "What does REST stand for in REST API?",
      options: [
        "Representational State Transfer",
        "Remote Execution State Transfer",
        "Real-time Event Streaming Technology",
        "Response-Encoded Server Transactions",
      ],
      correctIndex: 0,
    },
    {
      id: "web5",
      text: "Which HTML tag is used to define an internal style sheet?",
      options: ["<css>", "<script>", "<style>", "<link>"],
      correctIndex: 2,
    },
    {
      id: "web6",
      text: "What is WebSockets primarily used for?",
      options: [
        "Static file delivery",
        "Real-time bidirectional communication",
        "Database queries",
        "Image compression",
      ],
      correctIndex: 1,
    },
    {
      id: "web7",
      text: "What does JSON stand for?",
      options: [
        "JavaScript Object Notation",
        "Java Serialized Object Node",
        "JavaScript Oriented Network",
        "Java Standard Object Notation",
      ],
      correctIndex: 0,
    },
    {
      id: "web8",
      text: "Which CSS property controls text size?",
      options: ["font-weight", "text-size", "font-size", "letter-size"],
      correctIndex: 2,
    },
    {
      id: "web9",
      text: "What is the purpose of a CDN?",
      options: [
        "Content Delivery Network for faster distribution",
        "Central Database Node",
        "Code Distribution Node",
        "Component Design Network",
      ],
      correctIndex: 0,
    },
    {
      id: "web10",
      text: "Which method is used to make asynchronous HTTP requests in modern JavaScript?",
      options: ["XMLHttpRequest only", "fetch()", "ajax()", "http.get()"],
      correctIndex: 1,
    },
  ],
  ai_ml: [
    {
      id: "ai1",
      text: "What does GPU stand for?",
      options: [
        "General Processing Unit",
        "Graphics Processing Unit",
        "Global Program Utility",
        "Graphic Pixel Unit",
      ],
      correctIndex: 1,
    },
    {
      id: "ai2",
      text: "Which algorithm is commonly used for classification in ML?",
      options: ["Linear Regression", "K-Means", "Random Forest", "PCA"],
      correctIndex: 2,
    },
    {
      id: "ai3",
      text: "What is overfitting in machine learning?",
      options: [
        "Model performs well on test data only",
        "Model memorizes training data and performs poorly on new data",
        "Model has too few parameters",
        "Model training takes too long",
      ],
      correctIndex: 1,
    },
    {
      id: "ai4",
      text: "What is a neural network's activation function used for?",
      options: [
        "Data preprocessing",
        "Introducing non-linearity into the model",
        "Weight initialization",
        "Loss calculation",
      ],
      correctIndex: 1,
    },
    {
      id: "ai5",
      text: "What does NLP stand for in AI?",
      options: [
        "Neural Learning Protocol",
        "Natural Language Processing",
        "Network Layer Protocol",
        "Normalized Learning Process",
      ],
      correctIndex: 1,
    },
    {
      id: "ai6",
      text: "Which technique involves training with labeled data?",
      options: [
        "Unsupervised learning",
        "Reinforcement learning",
        "Supervised learning",
        "Transfer learning",
      ],
      correctIndex: 2,
    },
    {
      id: "ai7",
      text: "What is the purpose of dropout in neural networks?",
      options: [
        "Remove slow neurons",
        "Prevent overfitting by randomly deactivating neurons",
        "Speed up training",
        "Reduce dataset size",
      ],
      correctIndex: 1,
    },
    {
      id: "ai8",
      text: "GPT stands for?",
      options: [
        "General Pre-trained Transformer",
        "Generative Pre-trained Transformer",
        "Global Processing Technology",
        "Gradient Processing Tool",
      ],
      correctIndex: 1,
    },
    {
      id: "ai9",
      text: "What is gradient descent used for?",
      options: [
        "Data visualization",
        "Optimizing model parameters to minimize loss",
        "Feature extraction",
        "Data normalization",
      ],
      correctIndex: 1,
    },
    {
      id: "ai10",
      text: "Which of these is a generative AI model type?",
      options: ["Decision Tree", "SVM", "GAN", "K-NN"],
      correctIndex: 2,
    },
  ],
  cybersecurity: [
    {
      id: "cyb1",
      text: "What does SQL Injection exploit?",
      options: [
        "Network packets",
        "Unsanitized database queries",
        "CPU vulnerabilities",
        "Encryption weaknesses",
      ],
      correctIndex: 1,
    },
    {
      id: "cyb2",
      text: "What is a zero-day vulnerability?",
      options: [
        "A vulnerability known for 0 days",
        "An unknown vulnerability with no patch",
        "A daily security scan",
        "An expired SSL certificate",
      ],
      correctIndex: 1,
    },
    {
      id: "cyb3",
      text: "What does HTTPS provide over HTTP?",
      options: [
        "Faster loading",
        "Encrypted communication",
        "Better SEO only",
        "Larger file transfer",
      ],
      correctIndex: 1,
    },
    {
      id: "cyb4",
      text: "What is a DDoS attack?",
      options: [
        "Stealing user credentials",
        "Distributing malware via email",
        "Overwhelming a server with traffic",
        "Decrypting encrypted data",
      ],
      correctIndex: 2,
    },
    {
      id: "cyb5",
      text: "What does VPN stand for?",
      options: [
        "Virtual Private Network",
        "Verified Public Node",
        "Variable Protocol Network",
        "Visual Packet Navigator",
      ],
      correctIndex: 0,
    },
    {
      id: "cyb6",
      text: "What is phishing?",
      options: [
        "Network scanning",
        "Tricking users into revealing credentials",
        "Brute force attack",
        "Code injection",
      ],
      correctIndex: 1,
    },
    {
      id: "cyb7",
      text: "What is two-factor authentication?",
      options: [
        "Using two passwords",
        "Verifying identity with two independent methods",
        "Two-step file encryption",
        "Dual server validation",
      ],
      correctIndex: 1,
    },
    {
      id: "cyb8",
      text: "What does a firewall do?",
      options: [
        "Speeds up internet",
        "Monitors and controls network traffic",
        "Encrypts hard drives",
        "Scans for viruses",
      ],
      correctIndex: 1,
    },
    {
      id: "cyb9",
      text: "What is ransomware?",
      options: [
        "Free open-source software",
        "Malware that encrypts files and demands payment",
        "A network protocol",
        "Anti-virus software",
      ],
      correctIndex: 1,
    },
    {
      id: "cyb10",
      text: "What is the purpose of a salt in password hashing?",
      options: [
        "Speed up hashing",
        "Prevent rainbow table attacks",
        "Compress passwords",
        "Encrypt the database",
      ],
      correctIndex: 1,
    },
  ],
  data_science: [
    {
      id: "ds1",
      text: "What is the median of the dataset: [3, 7, 5, 1, 9]?",
      options: ["3", "5", "7", "6"],
      correctIndex: 1,
    },
    {
      id: "ds2",
      text: "What does pandas library in Python primarily help with?",
      options: [
        "Machine learning models",
        "Data manipulation and analysis",
        "Web scraping",
        "Image processing",
      ],
      correctIndex: 1,
    },
    {
      id: "ds3",
      text: "What is a p-value in statistics?",
      options: [
        "Probability of the null hypothesis being true given the data",
        "Percentage variance",
        "Power value of a test",
        "Population value",
      ],
      correctIndex: 0,
    },
    {
      id: "ds4",
      text: "Which chart is best for showing the distribution of a continuous variable?",
      options: ["Pie chart", "Bar chart", "Histogram", "Line chart"],
      correctIndex: 2,
    },
    {
      id: "ds5",
      text: "What is data normalization?",
      options: [
        "Removing duplicates",
        "Scaling data to a standard range",
        "Filling missing values",
        "Sorting data",
      ],
      correctIndex: 1,
    },
    {
      id: "ds6",
      text: "What does correlation measure?",
      options: [
        "Causation between variables",
        "Strength and direction of linear relationship",
        "Data spread",
        "Sample size",
      ],
      correctIndex: 1,
    },
    {
      id: "ds7",
      text: "What is a feature in ML terminology?",
      options: [
        "An input variable used for prediction",
        "A model output",
        "A training epoch",
        "A test result",
      ],
      correctIndex: 0,
    },
    {
      id: "ds8",
      text: "Which Python library is commonly used for data visualization?",
      options: ["NumPy", "Scikit-learn", "Matplotlib", "TensorFlow"],
      correctIndex: 2,
    },
    {
      id: "ds9",
      text: "What is the purpose of cross-validation?",
      options: [
        "Speed up training",
        "Assess model generalization on unseen data",
        "Reduce dataset size",
        "Normalize features",
      ],
      correctIndex: 1,
    },
    {
      id: "ds10",
      text: "What does ETL stand for in data engineering?",
      options: [
        "Extract, Transform, Load",
        "Evaluate, Test, Launch",
        "Export, Transfer, Link",
        "Estimate, Train, Log",
      ],
      correctIndex: 0,
    },
  ],
  movies: [
    {
      id: "mov1",
      text: "Which film won the Academy Award for Best Picture in 2020?",
      options: ["1917", "Joker", "Parasite", "Ford v Ferrari"],
      correctIndex: 2,
    },
    {
      id: "mov2",
      text: "Who directed Inception (2010)?",
      options: [
        "Steven Spielberg",
        "Christopher Nolan",
        "James Cameron",
        "Denis Villeneuve",
      ],
      correctIndex: 1,
    },
    {
      id: "mov3",
      text: 'In which movie does the character "Tyler Durden" appear?',
      options: ["American Psycho", "The Matrix", "Fight Club", "Se7en"],
      correctIndex: 2,
    },
    {
      id: "mov4",
      text: 'Which streaming platform produced "Stranger Things"?',
      options: ["HBO", "Disney+", "Netflix", "Amazon Prime"],
      correctIndex: 2,
    },
    {
      id: "mov5",
      text: "What is the highest-grossing film of all time (unadjusted)?",
      options: [
        "Titanic",
        "Avengers: Endgame",
        "Avatar",
        "Star Wars: The Force Awakens",
      ],
      correctIndex: 2,
    },
    {
      id: "mov6",
      text: 'The TV series "Breaking Bad" is set in which US city?',
      options: ["Los Angeles", "Albuquerque", "Phoenix", "Denver"],
      correctIndex: 1,
    },
    {
      id: "mov7",
      text: "Who played Tony Stark/Iron Man in the MCU?",
      options: [
        "Chris Evans",
        "Robert Downey Jr.",
        "Chris Hemsworth",
        "Mark Ruffalo",
      ],
      correctIndex: 1,
    },
    {
      id: "mov8",
      text: "Which series follows a chemistry teacher turned drug kingpin?",
      options: ["Ozark", "Narcos", "Breaking Bad", "The Wire"],
      correctIndex: 2,
    },
    {
      id: "mov9",
      text: 'In "The Dark Knight", who played the Joker?',
      options: [
        "Jack Nicholson",
        "Jared Leto",
        "Heath Ledger",
        "Joaquin Phoenix",
      ],
      correctIndex: 2,
    },
    {
      id: "mov10",
      text: 'Which film features the quote "You can\'t handle the truth!"?',
      options: ["A Few Good Men", "The Godfather", "Goodfellas", "Heat"],
      correctIndex: 0,
    },
  ],
  music: [
    {
      id: "mus1",
      text: 'Which artist released the album "Thriller" in 1982?',
      options: ["Prince", "Madonna", "Michael Jackson", "David Bowie"],
      correctIndex: 2,
    },
    {
      id: "mus2",
      text: "How many Grammys has Beyoncé won (as of 2024)?",
      options: ["28", "32", "36", "40"],
      correctIndex: 1,
    },
    {
      id: "mus3",
      text: 'Which band wrote the song "Bohemian Rhapsody"?',
      options: ["Led Zeppelin", "Queen", "The Beatles", "Pink Floyd"],
      correctIndex: 1,
    },
    {
      id: "mus4",
      text: 'What is Taylor Swift\'s "Eras Tour" known for?',
      options: [
        "Being the longest concert ever",
        "Highest-grossing concert tour in history",
        "First virtual reality tour",
        "First world tour with AI performances",
      ],
      correctIndex: 1,
    },
    {
      id: "mus5",
      text: "Which platform pays artists per stream?",
      options: ["YouTube Music", "Spotify", "Both A and B", "SoundCloud only"],
      correctIndex: 2,
    },
    {
      id: "mus6",
      text: "What genre is Kendrick Lamar known for?",
      options: ["R&B", "Hip-Hop/Rap", "Pop", "Jazz"],
      correctIndex: 1,
    },
    {
      id: "mus7",
      text: 'Which artist is known as the "Queen of Pop"?',
      options: ["Lady Gaga", "Rihanna", "Madonna", "Adele"],
      correctIndex: 2,
    },
    {
      id: "mus8",
      text: "BTS is a K-pop group from which country?",
      options: ["Japan", "China", "South Korea", "Thailand"],
      correctIndex: 2,
    },
    {
      id: "mus9",
      text: "Which decade saw the birth of Hip-Hop culture?",
      options: ["1960s", "1970s", "1980s", "1990s"],
      correctIndex: 1,
    },
    {
      id: "mus10",
      text: "Which song by The Weeknd has the most Spotify streams?",
      options: [
        "Starboy",
        "Can't Feel My Face",
        "Blinding Lights",
        "Save Your Tears",
      ],
      correctIndex: 2,
    },
  ],
  sports: [
    {
      id: "spt1",
      text: "How many players are on a basketball team on the court at one time?",
      options: ["4", "5", "6", "7"],
      correctIndex: 1,
    },
    {
      id: "spt2",
      text: "Which country has won the most FIFA World Cup titles?",
      options: ["Germany", "Italy", "Brazil", "Argentina"],
      correctIndex: 2,
    },
    {
      id: "spt3",
      text: 'In tennis, what is a "love" score?',
      options: ["Tie game", "Zero points", "Final set", "Winning shot"],
      correctIndex: 1,
    },
    {
      id: "spt4",
      text: "How many events make up the Olympic decathlon?",
      options: ["8", "10", "12", "7"],
      correctIndex: 1,
    },
    {
      id: "spt5",
      text: "LeBron James plays which sport?",
      options: ["Football", "Baseball", "Basketball", "Tennis"],
      correctIndex: 2,
    },
    {
      id: "spt6",
      text: "How long is a standard marathon in kilometers?",
      options: ["40 km", "42.195 km", "45 km", "38 km"],
      correctIndex: 1,
    },
    {
      id: "spt7",
      text: "Which country invented cricket?",
      options: ["Australia", "India", "England", "South Africa"],
      correctIndex: 2,
    },
    {
      id: "spt8",
      text: "What shape is a baseball diamond?",
      options: ["Circle", "Square", "Rectangle", "Triangle"],
      correctIndex: 1,
    },
    {
      id: "spt9",
      text: "How many gold medals did Usain Bolt win at the Olympics?",
      options: ["6", "7", "8", "9"],
      correctIndex: 2,
    },
    {
      id: "spt10",
      text: "What sport does Serena Williams play?",
      options: ["Golf", "Tennis", "Badminton", "Squash"],
      correctIndex: 1,
    },
  ],
  memes: [
    {
      id: "mem1",
      text: 'What is the name of the famous "This is Fine" meme dog sitting in?',
      options: ["Rain", "A burning room", "A flood", "A hot car"],
      correctIndex: 1,
    },
    {
      id: "mem2",
      text: "Which platform is most known for launching viral memes?",
      options: ["Facebook", "LinkedIn", "Reddit", "Pinterest"],
      correctIndex: 2,
    },
    {
      id: "mem3",
      text: 'What does "AFK" mean in internet slang?',
      options: [
        "Always Finding Knowledge",
        "Away From Keyboard",
        "Actual Fake Knowledge",
        "Asking For Kindness",
      ],
      correctIndex: 1,
    },
    {
      id: "mem4",
      text: 'What animal is associated with the "Doge" meme?',
      options: ["Cat", "Hamster", "Shiba Inu dog", "Bunny"],
      correctIndex: 2,
    },
    {
      id: "mem5",
      text: 'What does "TBH" stand for?',
      options: [
        "To Be Heard",
        "To Be Honest",
        "Try Being Helpful",
        "The Best Here",
      ],
      correctIndex: 1,
    },
    {
      id: "mem6",
      text: 'Which phrase is associated with the "Rick Roll" meme?',
      options: [
        "Never gonna give you up",
        "All your base are belong to us",
        "Deal with it",
        "Ermahgerd",
      ],
      correctIndex: 0,
    },
    {
      id: "mem7",
      text: 'What does "GG" mean in gaming culture?',
      options: ["Get Going", "Good Game", "Great Goal", "Got Ganked"],
      correctIndex: 1,
    },
    {
      id: "mem8",
      text: 'The "Distracted Boyfriend" meme format originated from what?',
      options: [
        "A movie screenshot",
        "A stock photo",
        "A video game",
        "A TV show",
      ],
      correctIndex: 1,
    },
    {
      id: "mem9",
      text: 'What does "FOMO" stand for?',
      options: [
        "Fear Of Missing Out",
        "First Online Media Output",
        "Feeling Of Maximum Output",
        "Fast Online Media Operations",
      ],
      correctIndex: 0,
    },
    {
      id: "mem10",
      text: 'The "Nyan Cat" meme features what type of animal?',
      options: ["Dog", "Cat", "Rabbit", "Fox"],
      correctIndex: 1,
    },
  ],
  marvel_anime: [
    {
      id: "man1",
      text: "Who is the alter ego of Iron Man?",
      options: ["Bruce Banner", "Tony Stark", "Steve Rogers", "Thor Odinson"],
      correctIndex: 1,
    },
    {
      id: "man2",
      text: "In which anime does the main character eat a Devil Fruit?",
      options: ["Naruto", "Bleach", "One Piece", "Dragon Ball Z"],
      correctIndex: 2,
    },
    {
      id: "man3",
      text: "What is the infinity gauntlet used for in Marvel?",
      options: [
        "Time travel only",
        "Wielding all six infinity stones for ultimate power",
        "Armor enhancement",
        "Controlling Thanos's army",
      ],
      correctIndex: 1,
    },
    {
      id: "man4",
      text: 'In "Attack on Titan", what are the three walls protecting humanity?',
      options: [
        "Maria, Rose, Sina",
        "Alpha, Beta, Gamma",
        "North, South, Central",
        "Titan, Human, Wall",
      ],
      correctIndex: 0,
    },
    {
      id: "man5",
      text: 'Which Marvel character is known as the "Sorcerer Supreme"?',
      options: ["Vision", "Doctor Strange", "Loki", "Scarlet Witch"],
      correctIndex: 1,
    },
    {
      id: "man6",
      text: "What is the name of Naruto's signature jutsu?",
      options: ["Chidori", "Rasengan", "Sharingan", "Susanoo"],
      correctIndex: 1,
    },
    {
      id: "man7",
      text: "In Marvel, what is vibranium most associated with?",
      options: [
        "Spider-Man's suit",
        "Captain America's shield",
        "Thor's hammer",
        "Iron Man's armor",
      ],
      correctIndex: 1,
    },
    {
      id: "man8",
      text: "Which anime features a teen that gains the power of shinigami (death gods)?",
      options: [
        "Fullmetal Alchemist",
        "One Punch Man",
        "Bleach",
        "Hunter x Hunter",
      ],
      correctIndex: 2,
    },
    {
      id: "man9",
      text: "Black Panther is the king of which fictional African nation?",
      options: ["Genosha", "Wakanda", "Latveria", "Sokovia"],
      correctIndex: 1,
    },
    {
      id: "man10",
      text: "In Dragon Ball Z, what transformation turns a Saiyan's hair golden?",
      options: ["Super Namekian", "Great Ape", "Super Saiyan", "Kaioken"],
      correctIndex: 2,
    },
  ],
  aptitude: [
    {
      id: "apt1",
      text: "If a train travels 60 km in 40 minutes, what is its speed in km/h?",
      options: ["70", "80", "90", "100"],
      correctIndex: 2,
    },
    {
      id: "apt2",
      text: "What is 15% of 200?",
      options: ["25", "30", "35", "40"],
      correctIndex: 1,
    },
    {
      id: "apt3",
      text: "Complete the sequence: 2, 6, 12, 20, __?",
      options: ["28", "30", "32", "36"],
      correctIndex: 1,
    },
    {
      id: "apt4",
      text: "If APPLE = 50, MANGO = 55, what is GRAPE?",
      options: ["50", "52", "48", "56"],
      correctIndex: 1,
    },
    {
      id: "apt5",
      text: "A man walks 3 km north, 4 km east. How far is he from start?",
      options: ["5 km", "6 km", "7 km", "4 km"],
      correctIndex: 0,
    },
    {
      id: "apt6",
      text: "Find the odd one out: 8, 27, 64, 100, 125",
      options: ["8", "27", "100", "125"],
      correctIndex: 2,
    },
    {
      id: "apt7",
      text: "If 6 workers complete a job in 12 days, how many days for 9 workers?",
      options: ["6", "7", "8", "9"],
      correctIndex: 2,
    },
    {
      id: "apt8",
      text: "What comes next: A, C, F, J, O, __?",
      options: ["U", "V", "T", "W"],
      correctIndex: 0,
    },
    {
      id: "apt9",
      text: "A clock shows 3:15. What is the angle between the hands?",
      options: ["7.5°", "0°", "15°", "30°"],
      correctIndex: 0,
    },
    {
      id: "apt10",
      text: "How many faces does a cube have?",
      options: ["4", "6", "8", "12"],
      correctIndex: 1,
    },
  ],
  general_knowledge: [
    {
      id: "gk1",
      text: "What is the capital city of Australia?",
      options: ["Sydney", "Melbourne", "Canberra", "Brisbane"],
      correctIndex: 2,
    },
    {
      id: "gk2",
      text: 'Which planet is known as the "Red Planet"?',
      options: ["Venus", "Jupiter", "Saturn", "Mars"],
      correctIndex: 3,
    },
    {
      id: "gk3",
      text: "How many bones are in an adult human body?",
      options: ["186", "206", "226", "246"],
      correctIndex: 1,
    },
    {
      id: "gk4",
      text: "What is the chemical symbol for gold?",
      options: ["Go", "Gd", "Au", "Ag"],
      correctIndex: 2,
    },
    {
      id: "gk5",
      text: "Which ocean is the largest?",
      options: ["Atlantic", "Indian", "Arctic", "Pacific"],
      correctIndex: 3,
    },
    {
      id: "gk6",
      text: "Which country has the longest coastline?",
      options: ["Russia", "USA", "Canada", "Australia"],
      correctIndex: 2,
    },
    {
      id: "gk7",
      text: "What is the hardest natural substance on Earth?",
      options: ["Gold", "Iron", "Diamond", "Platinum"],
      correctIndex: 2,
    },
    {
      id: "gk8",
      text: "The Great Wall of China was primarily built during which dynasty?",
      options: ["Tang", "Song", "Ming", "Qin"],
      correctIndex: 2,
    },
    {
      id: "gk9",
      text: "How many continents are there on Earth?",
      options: ["5", "6", "7", "8"],
      correctIndex: 2,
    },
    {
      id: "gk10",
      text: "What gas do plants absorb during photosynthesis?",
      options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"],
      correctIndex: 2,
    },
  ],
  startup: [
    {
      id: "strt1",
      text: "What does MVP stand for in startup terminology?",
      options: [
        "Maximum Viable Product",
        "Minimum Viable Product",
        "Most Valuable Player",
        "Minimum Valuable Prototype",
      ],
      correctIndex: 1,
    },
    {
      id: "strt2",
      text: 'What is "product-market fit"?',
      options: [
        "When product design matches market trends",
        "When a product satisfies a strong market demand",
        "When pricing matches competitor rates",
        "When the product launches in multiple markets",
      ],
      correctIndex: 1,
    },
    {
      id: "strt3",
      text: "What is venture capital?",
      options: [
        "Business loans from banks",
        "Funding from investors for equity in startups",
        "Government grants",
        "Crowdfunding campaigns",
      ],
      correctIndex: 1,
    },
    {
      id: "strt4",
      text: 'What does "pivot" mean for a startup?',
      options: [
        "Raising more capital",
        "Changing business strategy based on feedback",
        "Hiring new leadership",
        "Going public (IPO)",
      ],
      correctIndex: 1,
    },
    {
      id: "strt5",
      text: "What is bootstrapping a startup?",
      options: [
        "Building it with no team",
        "Funding it yourself without external investment",
        "Starting with government support",
        "Copying a successful model",
      ],
      correctIndex: 1,
    },
    {
      id: "strt6",
      text: "What does ARR stand for in SaaS?",
      options: [
        "Annual Revenue Rate",
        "Annual Recurring Revenue",
        "Average Return Rate",
        "Automated Revenue Reporting",
      ],
      correctIndex: 1,
    },
    {
      id: "strt7",
      text: "What is churn rate?",
      options: [
        "Revenue growth rate",
        "Customer acquisition cost",
        "Percentage of customers who stop using the service",
        "Monthly active users",
      ],
      correctIndex: 2,
    },
    {
      id: "strt8",
      text: "Y Combinator is a famous?",
      options: [
        "Tech conference",
        "Startup accelerator",
        "Venture capital firm",
        "Business school",
      ],
      correctIndex: 1,
    },
    {
      id: "strt9",
      text: "What does B2B mean?",
      options: [
        "Back to Basics",
        "Business to Business",
        "Brand to Buyer",
        "Budget to Backlog",
      ],
      correctIndex: 1,
    },
    {
      id: "strt10",
      text: 'What is "growth hacking"?',
      options: [
        "Hacking competitor systems for insights",
        "Creative low-cost strategies to grow users rapidly",
        "A software engineering method",
        "Manipulating SEO rankings",
      ],
      correctIndex: 1,
    },
  ],
  space_science: [
    {
      id: "spc1",
      text: "What is the closest star to Earth (besides the Sun)?",
      options: ["Sirius", "Proxima Centauri", "Betelgeuse", "Alpha Centauri A"],
      correctIndex: 1,
    },
    {
      id: "spc2",
      text: "What is a black hole's point of no return called?",
      options: [
        "Singularity",
        "Event Horizon",
        "Schwarzschild radius",
        "Gravitational lensing",
      ],
      correctIndex: 1,
    },
    {
      id: "spc3",
      text: "Which space agency launched the Hubble Space Telescope?",
      options: ["ESA", "Roscosmos", "NASA", "JAXA"],
      correctIndex: 2,
    },
    {
      id: "spc4",
      text: "What is the speed of light in a vacuum (approx)?",
      options: ["200,000 km/s", "300,000 km/s", "400,000 km/s", "150,000 km/s"],
      correctIndex: 1,
    },
    {
      id: "spc5",
      text: "What is the name of the force that shapes galaxies and dark matter indicates?",
      options: [
        "Electromagnetic force",
        "Strong nuclear force",
        "Gravity",
        "Weak nuclear force",
      ],
      correctIndex: 2,
    },
    {
      id: "spc6",
      text: "How old is the universe approximately?",
      options: [
        "4.5 billion years",
        "10 billion years",
        "13.8 billion years",
        "20 billion years",
      ],
      correctIndex: 2,
    },
    {
      id: "spc7",
      text: "What is the largest planet in our solar system?",
      options: ["Saturn", "Neptune", "Uranus", "Jupiter"],
      correctIndex: 3,
    },
    {
      id: "spc8",
      text: "What causes the seasons on Earth?",
      options: [
        "Distance from the Sun",
        "Earth's axial tilt",
        "Moon's orbit",
        "Solar flares",
      ],
      correctIndex: 1,
    },
    {
      id: "spc9",
      text: "What is a light-year?",
      options: [
        "Time light takes to travel one year",
        "Distance light travels in one year",
        "Speed of light per year",
        "Brightness measurement",
      ],
      correctIndex: 1,
    },
    {
      id: "spc10",
      text: "Which planet has the most moons?",
      options: ["Jupiter", "Saturn", "Uranus", "Neptune"],
      correctIndex: 1,
    },
  ],
  history: [
    {
      id: "his1",
      text: "In which year did World War I begin?",
      options: ["1910", "1914", "1918", "1939"],
      correctIndex: 1,
    },
    {
      id: "his2",
      text: 'Which empire was known as the "empire on which the sun never sets"?',
      options: [
        "Roman Empire",
        "Ottoman Empire",
        "British Empire",
        "Mongol Empire",
      ],
      correctIndex: 2,
    },
    {
      id: "his3",
      text: "The Battle of Waterloo ended whose reign?",
      options: [
        "Julius Caesar",
        "Napoleon Bonaparte",
        "Alexander the Great",
        "Genghis Khan",
      ],
      correctIndex: 1,
    },
    {
      id: "his4",
      text: "In which country did the first atomic bomb drop (WWII)?",
      options: ["Germany", "Russia", "Japan", "France"],
      correctIndex: 2,
    },
    {
      id: "his5",
      text: "The Cold War was primarily between which two superpowers?",
      options: [
        "USA and China",
        "UK and Germany",
        "USA and USSR",
        "France and Russia",
      ],
      correctIndex: 2,
    },
    {
      id: "his6",
      text: "What year did the Berlin Wall fall?",
      options: ["1987", "1989", "1991", "1993"],
      correctIndex: 1,
    },
    {
      id: "his7",
      text: "Who was the first emperor of China?",
      options: ["Kublai Khan", "Confucius", "Qin Shi Huang", "Sun Tzu"],
      correctIndex: 2,
    },
    {
      id: "his8",
      text: "The French Revolution began in which year?",
      options: ["1776", "1789", "1799", "1815"],
      correctIndex: 1,
    },
    {
      id: "his9",
      text: "Which ancient wonder was located in Alexandria?",
      options: [
        "Colossus of Rhodes",
        "Lighthouse of Alexandria",
        "Hanging Gardens",
        "Temple of Artemis",
      ],
      correctIndex: 1,
    },
    {
      id: "his10",
      text: "Who led India to independence from British rule?",
      options: [
        "Jawaharlal Nehru",
        "Bhagat Singh",
        "Mahatma Gandhi",
        "Subhas Chandra Bose",
      ],
      correctIndex: 2,
    },
  ],
};

export function getQuestions(theme: SubTheme, count: number): Question[] {
  const pool = [...quizBank[theme]];
  // Shuffle using Fisher-Yates
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  return pool.slice(0, Math.min(count, pool.length));
}

export const themeLabels: Record<SubTheme, string> = {
  programming: "Programming Languages",
  webdev: "Web Development",
  ai_ml: "AI & Machine Learning",
  cybersecurity: "Cybersecurity",
  data_science: "Data Science",
  movies: "Movies & Series",
  music: "Music & Pop Culture",
  sports: "Sports",
  memes: "Memes & Internet",
  marvel_anime: "Marvel / Anime",
  aptitude: "Aptitude & Logic",
  general_knowledge: "General Knowledge",
  startup: "Startup & Business",
  space_science: "Space & Science",
  history: "History Battles",
};
